### ISSUE TITLE
How to create a CSR and import the certificate after it is signed

### ISSUE THREAD

**Issue by jariq** [jariq/Pkcs11Admin#14]
I've received following question via e-mail:

> Do you have a guide on how to create a csr and import the certificate after it is signed in the Admin tool?

I'll answer the question here so the answer is available for future reference.

**Comment by jariq** [comment]
1. **Run Pkcs11Admin**
1.1 Execute Pkcs11Admin
1.2 Load desired PKCS#11 library
2. **Authenticate with token**
2.2 Select desired slot via "Slot" menu
2.3. Authenticate via `Token > Login > User login ...` menu item
3. **Generate new RSA key pair**
3.1 Select `Object > New... > Key ...` menu item
3.2 Leave key type set to `CKK_RSA`
3.3 Set desired value of `CKA_LABEL` attribute for both private and public keys e.g. `testlabel`
3.4 Set desired value of `CKA_ID` attribute for both private and public keys e.g. `testid`
3.5 Click "Generate" button to generate new RSA key pair
4. **Generate CSR**
4.1 Select RSA private key with `testlabel` label value in "Keys" tab
4.2 Select `Object > New > Certificate signing request ...` menu item
4.3 Add desired subject entries for future certificate e.g.
4.3.1 Add `commonName` entry type with `John Doe` entry value and click "Add" button
4.3.2 Add `countryName` entry type with `SK` entry value and click "Add" button
4.4 Click "Generate" button and choose the file where CSR will be saved
5. **Get certificate**
5.1 Send CSR file to your CA so they can issue certificate for you
5.2 Get CRT/CER/DER file with your certificate from CA
6. **Import certificate**
6.1 Select `Object > Import > Certificate ...` menu item
6.2 Make sure `CKA_LABEL` and `CKA_ID` attributes are set to the same value as in steps 3.3 and 3.4
6.3 Click "Create" button to create/import certificate object

**Comment by runes83** [comment]
Thanks for the guide.

When using a HSM, Is there a way to mark a Key so that in order to sign with it you have to have to verify with the partition ped key?

**Comment by jariq** [comment]
I'm not sure I fully understand what you are trying to achieve but if you require re-authentication on every key usage then try to set `CKA_ALWAYS_AUTHENTICATE` attribute of the private key object to `CK_TRUE` during the key generation process.

**Comment by runes83** [comment]
Is it possible to update CKA_ALWAYS_AUTHENTICATE  after the key have been created?

**Comment by jariq** [comment]
PKCS#11 v2.20 does not state anything about this. Try to modify attribute value and you will see if you receive an error.

**Comment by runes83** [comment]
When I try to edit in "Edit object attributes" I get CKR_ATTRIBUTE_TYPE_INVALID

Have tried using true, and 01 but the same error.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Net.Pkcs11Interop.Common.Pkcs11Exception: Method C_SetAttributeValue returned CKR_ATTRIBUTE_TYPE_INVALID
   at Net.Pkcs11Interop.HighLevelAPI41.Session.SetAttributeValue(ObjectHandle objectHandle, List`1 attributes)
   at Net.Pkcs11Admin.Pkcs11Slot.SaveObjectAttributes(Pkcs11ObjectInfo objectInfo, List`1 objectAttributes)
   at Net.Pkcs11Admin.WinForms.Dialogs.EditObjectDialog.EditAttributeValue()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jariq** [comment]
Seems it cannot be changed. Did you try to generate new key with this attribute?

**Comment by runes83** [comment]
@jariq I will try to create a new key.

**Comment by ghost** [comment]
There are keys, but I'm not sure the certificate is signed. Certificate private key attribute is false. 
Label                                 ID                   Certificate type                Private          Storage Size   
MUS_CER                          111111           CKC_X_509                      False              455
If this is the case, can I not use the private key in the signing process?

**Comment by jariq** [comment]
Closing after 14+ days of inactivity.
