### ISSUE TITLE
Click on Application>Refresh after loading without readers shows an error message

### ISSUE THREAD

**Issue by helpcrypto** [jariq/Pkcs11Admin#2]
1.- Load a library without readers attached using pkcs11-spy.
2.- Click on Refresh

BTW: Does it has any meaning to have all tabs enabled even with no reader present? (IMHO: disable them!)

**Comment by jariq** [comment]
This is already fixed in 6f862416d2165c6dcdfbb9f3d6ee1c9004d36f98.

It may not be obvious but tabs are disabled and because of that you cannot click any controls in them. However GUI toolkit (WinForms) does not prevent disabled tabs from being selected which is a known limitation that can be resolved for example by hiding the tab instead of disabling. But...

I have decided not to hide/show any tabs in runtime because tabs can be disabled also in other situations. For example: application successfully loaded library, token is present and certificates are being read from the device when suddenly unrecoverable exception occurs. The tab gets disabled and exception message is shown in the status bar when the tab is selected. With hidden tab there would be no place to show exception that prevented the tab from being populated with data.
