### ISSUE TITLE
Unnecesary call to C_GetSlotInfo (already done before)

### ISSUE THREAD

**Issue by helpcrypto** [jariq/Pkcs11Admin#5]
When loading the library, without a token present on reader, I see several calls to C_GetSlotInfo which are useleess if there are no token insertion/extractions events
eg: before invoking C_GetMechanismList

BTW: C_GetMechanismList shouldn't be invoked if there are no tokens

**Comment by jariq** [comment]
Thanks for reporting! Number of performed calls should now be decreased.

However when library is loaded C_GetSlotInfo needs to be called once for each reported slot because application needs to display list of available slot with their names. It is also called once when slot is "refreshed" which happens when user picks the slot from menu or when the first slot is picked automatically right after the library is loaded. So it is OK if C_GetSlotInfo is called "number_of_slots + 1" times right after the library is loaded.

Ad BTW: Some of the libraries I am testing the app with return list of supported mechanisms even if there is no token present and IMO it is OK in cases where library supports just one type of the token/card. But I agree this could cause some "misunderstandings" with libraries that supports multiple token types with different features so I've decided to adapt your idea and call C_GetMechanimList only when token is present.
